config:
    build_jobs: 32
    install_tree:
      root: $SPACK_USER_PREFIX/23.09/0.21.0
      projections:
        all: '{name}-{version}-{hash:7}'
    source_cache: $SPACK_USER_PREFIX/23.09/0.21.0/cache
    misc_cache: $SPACK_USER_PREFIX/23.09/0.21.0/cache
    install_missing_compilers: false
    suppress_gpg_warnings: true
    build_language: C

