modules:
  prefix_inspections:
    bin:
    - PATH
    man:
    - MANPATH
    share/man:
    - MANPATH
    share/aclocal:
    - ACLOCAL_PATH
    lib:
    - LD_LIBRARY_PATH
    lib64:
    - LD_LIBRARY_PATH
    lib/pkgconfig:
    - PKG_CONFIG_PATH
    lib64/pkgconfig:
    - PKG_CONFIG_PATH
    share/pkgconfig:
    - PKG_CONFIG_PATH
    ? ''
    : - CMAKE_PREFIX_PATH
  default:
    roots:
      tcl: $SPACK_USER_PREFIX/23.09/0.21.0/modules/tcl
    enable:
      - tcl
    tcl:
      hash_length: 3
      projections:
        all: '{name}/{version}-{compiler.name}'
      exclude:
      - cray-mpich
      - cray-libsci
      openblas:
        suffixes:
          openblas threads=openmp: omp
          openblas threads=pthreads: pthreads
          openblas threads=none: serial
      hpl:
        suffixes:
          hpl ^openblas: openblas
      zstd:
        suffixes:
          zstd ~programs: nobin
      binutils:
        suffixes:
          binutils +gold: gold
      xz:
        suffixes:
          xz +pic: pic
      elfutils:
        suffixes:
          elfutils +bzip2: compress
      trilinos:
        suffixes:
          trilinos +rocm: gpu
      kokkos:
        suffixes:
          kokkos +rocm: gpu
      chai:
        suffixes:
          chai +rocm: gpu
      raja:
        suffixes:
          raja +rocm: gpu
      umpire:
        suffixes:
          umpire +rocm: gpu
      gromacs:
        suffixes:
          gromacs +plumed: plumed

